// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANOQmnejQZmu5lw8WrGN9z4CEeFemqCpo',
    appId: '1:627572078452:web:1fbb389145154631711e21',
    messagingSenderId: '627572078452',
    projectId: 'bintam-40b1d',
    authDomain: 'bintam-40b1d.firebaseapp.com',
    storageBucket: 'bintam-40b1d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7WefImb7QSMmbtKsmSFM79r2RtfKipz8',
    appId: '1:627572078452:android:7ef94436e2c8c109711e21',
    messagingSenderId: '627572078452',
    projectId: 'bintam-40b1d',
    storageBucket: 'bintam-40b1d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYlfVe8I7bYf5sorvxZXZEAw2rFZr9cN8',
    appId: '1:627572078452:ios:bd7c358cbd7acabd711e21',
    messagingSenderId: '627572078452',
    projectId: 'bintam-40b1d',
    storageBucket: 'bintam-40b1d.firebasestorage.app',
    iosBundleId: 'com.example.bintam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYlfVe8I7bYf5sorvxZXZEAw2rFZr9cN8',
    appId: '1:627572078452:ios:bd7c358cbd7acabd711e21',
    messagingSenderId: '627572078452',
    projectId: 'bintam-40b1d',
    storageBucket: 'bintam-40b1d.firebasestorage.app',
    iosBundleId: 'com.example.bintam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANOQmnejQZmu5lw8WrGN9z4CEeFemqCpo',
    appId: '1:627572078452:web:3687b1732a125933711e21',
    messagingSenderId: '627572078452',
    projectId: 'bintam-40b1d',
    authDomain: 'bintam-40b1d.firebaseapp.com',
    storageBucket: 'bintam-40b1d.firebasestorage.app',
  );
}
